groups:
- name: prometheus-rule-group
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  - alert: APIHighRequestLatency
    expr: api_http_request_latencies_second{quantile="0.5"} > 1
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High request latency on {{ $labels.instance }}"
      description: "{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)"

  - alert: AlwaysFiringAlert
    expr: vector(1) > 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "This alert is always firing"
      description: "This alert is always firing (current value: {{ $value }}s)"

- name: prometheus-rule-group-2
  rules:
  - alert: AlwaysFiringAlert-2
    expr: vector(1) > 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "This alert is always firing"
      description: "This alert is always firing (current value: {{ $value }}s)"
